export default {
	estados: [
		{
			uf: "SP",
			cidades: [
				{
					nome: "São Paulo",
					bairros: [
						"Água Rasa",
						"Alto de Pinheiros",
						"Anhanguera",
						"Aricanduva",
						"Artur Alvim",
						"Barra Funda",
						"Bela Vista",
						"Belém",
						"Bom Retiro",
						"Brás",
						"Brasilândia",
						"Butantã",
						"Cachoeirinha",
						"Cambuci",
						"Campo Belo",
						"Campo Grande",
						"Campo Limpo",
						"Cangaiba",
						"Capão Redondo",
						"Carrão",
						"Casa Verde",
						"Cidade Ademar",
						"Cidade Dutra",
						"Cidade Lider",
						"Cidade Tiradentes",
						"Consolação",
						"Cursino",
						"Ermelino Matarazzo",
						"Freguesia do Ó",
						"Grajaú",
						"Guaianases",
						"Moema",
						"Iguatemi",
						"Ipiranga",
						"Itaim Bibi",
						"Itaim Paulista",
						"Itaquera",
						"Jabaquara",
						"Jaçanã",
						"Jaguara",
						"Jaguaré",
						"Jaraguá",
						"Jardim Ângela",
						"Jardim Helena",
						"Jardim Paulista",
						"Jardim São Luís",
						"José Bonifácio",
						"Lapa",
						"Liberdade",
						"Limão",
						"Mandaqui",
						"Marsilac",
						"Mooca",
						"Morumbi",
						"Parelheiros",
						"Pari",
						"Parque do Carmo",
						"Pedreira",
						"Penha",
						"Perdizes",
						"Perus",
						"Pinheiros",
						"Pirituba",
						"Ponte Rasa",
						"Raposo Tavares",
						"República",
						"Rio Pequeno",
						"Sacomã",
						"Santa Cecília",
						"Santana",
						"Santo Amaro",
						"São Lucas",
						"São Mateus",
						"São Miguel",
						"São Rafael",
						"Sapopemba",
						"Saúde",
						"Sé",
						"Socorro",
						"Tatuapé",
						"Tremembé",
						"Tucuruvi",
						"Vila Andrade",
						"Vila Curuçá",
						"Vila Formosa",
						"Vila Guilherme",
						"Vila Jacuí",
						"Vila Leopoldina",
						"Vila Maria",
						"Vila Mariana",
						"Vila Matilde",
						"Vila Medeiros",
						"Vila Prudente",
						"Vila Sônia",
						"São Domingos",
						"Lajeado"
					]
				},
				{
					nome: "Barueri",
					bairros: [
						"Aldeia Serra",
						"Alphaville Centro Apoio I",
						"Alphaville Comercial",
						"Alphaville Conde I",
						"Alphaville Condomínio I",
						"Alphaville Condomínio Ii",
						"Alphaville Empresarial ",
						"Alphaville Industrial",
						"Alphaville Residencial Dois",
						"Alphaville Residencial Plus",
						"Alphaville Residencial Um",
						"Alphaville Residencial Zero",
						"Bethaville I",
						"Bethaville Ii",
						"Centro",
						"Centro administrativo Coml Jubran",
						"Centro administrativo Empresário Tamboré",
						"Centro Comercial",
						"Centro Empresarial",
						"Chácara Peroba",
						"Chs Marco",
						"Condomínio C C Alphaville",
						"Condomínio Centro Comercial Alameda",
						"Empresarial 18 do Forte",
						"Jardim Alberto",
						"Jardim Audir",
						"Jardim Barueri",
						"Jardim Belval",
						"Jardim Califórnia",
						"Jardim do Líbano",
						"Jardim dos Camargos",
						"Jardim Esperança",
						"Jardim Flórida",
						"Jardim Graziela",
						"Jardim Iracema",
						"Jardim Itaparica",
						"Jardim Itaquiti",
						"Jardim Júlio",
						"Jardim Maria Cristina",
						"Jardim Maria Helena",
						"Jardim Maria Tereza",
						"Jardim Mutinga",
						"Jardim Paraíso",
						"Jardim Paulista",
						"Jardim Regina Alice",
						"Jardim Santa Cecília",
						"Jardim Santa Mônica",
						"Jardim São José",
						"Jardim São Pedro",
						"Jardim São Silvestre",
						"Jardim Silveira",
						"Jardim Timbauhy",
						"Jardim Tupã",
						"Jardim Tupan",
						"Jardim Tupanci",
						"Melville Empresarial I E II",
						"Morada dos Pássaros",
						"Nova Aldeinha",
						"Núcleo Residencial Célia Mota",
						"Outeiro São Fernando",
						"Parque Camargos",
						"Parque das Nações",
						"Parque dos Camargos",
						"Parque Esmeralda",
						"Parque Imperial",
						"Parque Ribeiro de Lima",
						"Parque Ribeiro Lima",
						"Parque Santa Luzia",
						"Parque Viana",
						"Praça Aldeia Serra I",
						"Recanto Phrynea",
						"Residencial das Estrelas",
						"Residencial Morada dos Lagos",
						"Residencial Morada Lagos",
						"Residencial Tamboré",
						"São Fernando Residência",
						"Tamboré",
						"Vale do Sol",
						"Vila Barros",
						"Vila Boa Vista",
						"Vila Ceres",
						"Vila Conceição",
						"Vila Creti",
						"Vila Engenho Novo",
						"Vila Industrial",
						"Vila Iracema",
						"Vila Militar",
						"Vila Morellato",
						"Vila Nilva",
						"Vila Nossa Senhora Aparecida",
						"Vila Nova",
						"Vila Nova Barueri",
						"Vila Osmany",
						"Vila Pindorama",
						"Vila Porto",
						"Vila Pouso Alegre",
						"Vila São Francisco",
						"Vila São João",
						"Vila São Jorge",
						"Vila São Luiz",
						"Vila São Miguel",
						"Vila São Silvestre",
						"Vila Sargento José de Paula",
						"Vila Silveira",
						"Vila Sol",
						"Vila Universal",
						"Vila Viana",
						"Votupoca"
					]
				},
				{
					nome: "Carapicuíba",
					bairros: [
						"Águas da Fazendinha",
						"Aldeia da Fazendinha",
						"Altos Santa Lúcia",
						"Bela Vista",
						"Centro",
						"Chácara Adriana Aparecida",
						"Chácara das Candeias",
						"Chácara das Flores",
						"Chácara das Paineiras",
						"Chácara de La Rocca",
						"Chácara do Refúgio",
						"Chácara dos Junqueiras",
						"Chácara dos Lagos",
						"Chácara Granja Velha",
						"Chácara Moinho Velho",
						"Chácara Quiriri",
						"Chácara Santa Lúcia",
						"Chácara Santa Lúcia dos Ypes",
						"Chácara São João",
						"Chácara Vale do Rio Cotia",
						"Cidade Ariston Estela Azevedo",
						"Conjunto Habitacional 120 Casas",
						"Conjunto Habitacional Presidente Castelo Branco",
						"Granja Santa Maria",
						"Guapiuva",
						"Jardim Alfredo Soncini",
						"Jardim Alice",
						"Jardim Ampermag",
						"Jardim Ana Estela",
						"Jardim Ana Maria",
						"Jardim Ângela Maria",
						"Jardim Angélica",
						"Jardim Boa Vista",
						"Jardim Bom Pastor",
						"Jardim Bom Sucesso",
						"Jardim Carapicuíba",
						"Jardim Cecília Cristina",
						"Jardim Cibele",
						"Jardim Colonial",
						"Jardim Copiuva",
						"Jardim D'angelo",
						"Jardim das Belezas",
						"Jardim das Palmeiras",
						"Jardim das Pedras",
						"Jardim dos Manacás",
						"Jardim Elzinha",
						"Jardim Ercy",
						"Jardim Felipe",
						"Jardim Guiomar",
						"Jardim Helena",
						"Jardim Hermínia",
						"Jardim Leonor",
						"Jardim Leopoldina",
						"Jardim Lice",
						"Jardim Maria Beatriz",
						"Jardim Maria Helena",
						"Jardim Maria Rita",
						"Jardim Marilu",
						"Jardim Mesquita",
						"Jardim Novo Horizonte",
						"Jardim Paulista",
						"Jardim Pedras",
						"Jardim Pignatary",
						"Jardim Planalto",
						"Jardim Popular",
						"Jardim Primavera",
						"Jardim Primeiro de Maio",
						"Jardim Primeiro Maio",
						"Jardim Rosa Maria",
						"Jardim Roseli",
						"Jardim Sandra Regina",
						"Jardim Santa Brígida",
						"Jardim Santa Rita",
						"Jardim Santa Tereza",
						"Jardim Santo Estêvão",
						"Jardim São Pedro",
						"Jardim Ster-za",
						"Jardim Tonato",
						"Jardim Tucunduva",
						"Jardim Yaya",
						"Nova Fazendinha",
						"Palos Verdes",
						"Parque Flórida",
						"Parque Ideal",
						"Parque Jandaia",
						"Parque José Alex André",
						"Parque Primavera",
						"Parque Roseira",
						"Parque Sampaio Viana",
						"Parque Santa Teresa",
						"Parque Santa Tereza",
						"Pousada dos Bandeirantes",
						"Recantinho",
						"Recanto Campy",
						"Recanto Impla",
						"Residencial Euroville",
						"Santa Terezinha",
						"Sítio Guarehy",
						"Sítio Pereira Leite",
						"Terras do Madeira",
						"Vila América",
						"Vila Anunciata",
						"Vila Appia Antica",
						"Vila Artem",
						"Vila Bela",
						"Vila Bolívar",
						"Vila Caldas",
						"Vila Capriotti",
						"Vila Clara",
						"Vila Conquista",
						"Vila Creti",
						"Vila Cristina",
						"Vila da Oportunidade",
						"Vila Dirce",
						"Vila Diva",
						"Vila dos Andrades",
						"Vila Ema",
						"Vila Ester",
						"Vila Freitas",
						"Vila Gobbi",
						"Vila Guarani",
						"Vila Gustavo Correia",
						"Vila Helemar",
						"Vila Helena",
						"Vila Iza",
						"Vila Janete",
						"Vila Jussara",
						"Vila Leopoldo",
						"Vila Lisboa",
						"Vila Lourdes",
						"Vila Marcondes",
						"Vila Margarida",
						"Vila Maria Helena",
						"Vila Martins",
						"Vila Menk",
						"Vila Mercês",
						"Vila Mor",
						"Vila Municipal",
						"Vila Nossa Senhora Aparecida",
						"Vila Olivina",
						"Vila Oportunidade",
						"Vila Quintino",
						"Vila Rosa",
						"Vila Santa Lúcia",
						"Vila Santa Terezinha",
						"Vila Santo Antônio",
						"Vila São Jorge",
						"Vila São José",
						"Vila Silva Ribeiro",
						"Vila Silviania",
						"Vila Sul Americana",
						"Vila Tambory",
						"Vila Teresa",
						"Vila Terezinha",
						"Vila Três Irmãos",
						"Vila Veloso",
						"Vilarejo"
					]
				},
				{
					nome: "Itapevi",
					bairros: [
						"Abreus",
						"Amador Bueno",
						"Ambuita",
						"Atendimento Precario IV",
						"Bairro São João",
						"Caminho do Sol",
						"Centro",
						"Chácara Monte Serrat",
						"Chácara Santa Cecília",
						"Chácara Vitápolis",
						"Chs Monte Serrat",
						"Chs Primavera",
						"Cidade da Saúde",
						"Cohab",
						"Colinas de Itapevi",
						"Condomínio Nova São Paulo",
						"Condomínio Refúgio dos Pinheiros",
						"Condomínio Refúgio Pinheiros",
						"Conjunto Hab-setor D",
						"Conjunto Habitacional - Setor",
						"Conjunto Habitacional - Setor Area",
						"Conjunto Habitacional - Setor B",
						"Conjunto Habitacional - Setor D",
						"Estância São Francisco",
						"Ingahi",
						"Itaparica",
						"Itapevi",
						"Itaqui",
						"Jacucai ",
						"Jardim Alabama",
						"Jardim Amador Bueno",
						"Jardim Aurora",
						"Jardim Beatriz",
						"Jardim Bela Vista",
						"Jardim Briquet",
						"Jardim Cruzeiro",
						"Jardim da Rainha",
						"Jardim Dona Elvira",
						"Jardim Gioia",
						"Jardim Hokkaido",
						"Jardim Itacolomi",
						"Jardim Itaguassu",
						"Jardim Itapevi",
						"Jardim Itapoã",
						"Jardim Julieta",
						"Jardim Jurema",
						"Jardim Maria Cecília",
						"Jardim Maria Judite",
						"Jardim Marina",
						"Jardim Maristela",
						"Jardim Mirador",
						"Jardim Nova Cotia",
						"Jardim Nova Itapevi",
						"Jardim Paulista",
						"Jardim Portela",
						"Jardim Rainha",
						"Jardim Rosemary",
						"Jardim Ruth",
						"Jardim Santa Rita",
						"Jardim Santa Rita - 2a Parte",
						"Jardim Santa Rosa",
						"Jardim Santo Américo",
						"Jardim Santo Antônio",
						"Jardim São Carlos",
						"Jardim São Luiz",
						"Jardim São Marcos",
						"Jardim São Paulo",
						"Jardim Sorocabana",
						"Jardim Vitápolis",
						"Morada das Nuvens",
						"Nova Itapevi",
						"Parque Boa Esperança",
						"Parque Ciras",
						"Parque Itamarati",
						"Parque Mira Flores",
						"Parque Santo Antônio",
						"Parque Suburbano",
						"Parque Wey",
						"Polo Industrial",
						"Prox Jardim Cruzeiro",
						"Prox Jardim São Judas",
						"Quatro Encruzilhadas",
						"Recanto Verde Lagos",
						"Refúgio Pinheiros",
						"Residencial Colinas de São José",
						"Residencial Parque Itamarati",
						"Residencial Vale Sol",
						"Romaria",
						"São João",
						"Sapianta",
						"Tijoleiros",
						"Transurb",
						"Vila Aparecida",
						"Vila Áurea",
						"Vila Aurora",
						"Vila Belmira",
						"Vila das Flores",
						"Vila Dona Paulina",
						"Vila Doutor Cardoso",
						"Vila Elvira",
						"Vila Garcia",
						"Vila Lícia",
						"Vila Maria Christina",
						"Vila Monjolinho",
						"Vila Neofarm",
						"Vila Nova Itapevi",
						"Vila Olímpia",
						"Vila Olinda",
						"Vila Recanto Paulistano",
						"Vila Santa Flora",
						"Vila Santa Rita",
						"Vila Santo Antônio da Boa Vista",
						"Vila São Francisco - G 1 Área 3",
						"Vila São João"
					]
				},
				{
					nome: "Jandira",
					bairros: [
						"Altos de São Fernando",
						"Centro",
						"Chácara Vitápolis",
						"Chs do Peroba",
						"Fazenda Itaquiti",
						"Granja Alvorada",
						"Infant's Garden",
						"Jardim Alvorada",
						"Jardim Analândia",
						"Jardim Aurora",
						"Jardim Belmont",
						"Jardim Belval",
						"Jardim Bolívia",
						"Jardim Brotinho",
						"Jardim Camila",
						"Jardim Centenário",
						"Jardim Cristino",
						"Jardim das Margaridas",
						"Jardim do Golf I",
						"Jardim Europa",
						"Jardim Gabriela I",
						"Jardim Gabriela II",
						"Jardim Gabriela III",
						"Jardim Golf I",
						"Jardim Granja Alvorada",
						"Jardim Heneide",
						"Jardim Jandira",
						"Jardim Javaes",
						"Jardim Lindomar",
						"Jardim Margaridas",
						"Jardim Marília",
						"Jardim Mase",
						"Jardim Nossa Senhora de Fátima",
						"Jardim Nossa Senhora Fátima",
						"Jardim Novo Horizonte",
						"Jardim Palmeiras",
						"Jardim Patriarca",
						"Jardim Pedreira",
						"Jardim Rosa Emília",
						"Jardim Sagrado Coração",
						"Jardim Sagrado Coração de Jesus",
						"Jardim Sagrado Coração Jesus",
						"Jardim São João",
						"Jardim São Luiz",
						"Jardim São Paulo",
						"Jardim Sol Nascente",
						"Jardim Sorocabano",
						"Jardim Stella Maris",
						"Jardim Velho Sanazar",
						"Lago Cisnes",
						"Loteamento Jardim Alvorada",
						"Mirante de Jandira",
						"Mirante Jandira",
						"Nova Higienópolis",
						"Núcleo Micro I Poço Wilson",
						"Parque das Iglesias",
						"Parque dos Lagos",
						"Parque Nova Jandira",
						"Parque Santa Tereza",
						"Prox Parque Nova Jandira",
						"Prox Trevo Balneário Jardim",
						"Recanto Flores",
						"Sítio Pedra Bonita",
						"Sítio Pedra Branca",
						"Vale do Sol",
						"Vila Anita Costa",
						"Vila Cecília",
						"Vila Cristhino",
						"Vila Diogo Balhesteiro",
						"Vila Dolores Paschoalin",
						"Vila Dom Balhesteiro",
						"Vila Ercília",
						"Vila Esmeralda",
						"Vila Eugênia",
						"Vila Eunice",
						"Vila Godinho",
						"Vila Ipe",
						"Vila Lucinda",
						"Vila Makenzi",
						"Vila Márcia",
						"Vila Mercedes",
						"Vila Ouro Verde",
						"Vila Pedreira",
						"Vila Popi",
						"Vila Rolim",
						"Vila Santa Rosa",
						"Vila Santo Antônio",
						"Vila São Nicolau",
						"Vila Sol"
					]
				},
				{
					nome: "Osasco",
					bairros: [
						"Adalgisa",
						"Aliança",
						"Ayrosa",
						"Bacharel Jardim",
						"Bandeiras",
						"Baronesa",
						"Bela Vista",
						"Bonança",
						"Bonfim",
						"Bussocaba",
						"Centro",
						"Cidade das Flores",
						"Cidade Deus",
						"Cipava",
						"City Bussocaba",
						"Conceição",
						"Continental",
						"Helena Maria",
						"Iapi",
						"Industrial Anhanguera",
						"Jaguaribe",
						"Jardim Cirino",
						"Jardim D'abril",
						"Jardim das Flores",
						"Jardim Dom Abril",
						"Jardim Elvira",
						"Jardim Flores",
						"Jardim Itabau",
						"Jardim Marieta",
						"Jardim Nogueira",
						"Jardim Padroeira",
						"Jardim Piratininga",
						"Jardim Platina",
						"Jardim Primeiro de Maio",
						"Jardim Roberto",
						"Jardim Trabalhadores",
						"Jardim Turíbio",
						"Km 18",
						"Metalúrgicos",
						"Munhoz Jr",
						"Mutinga",
						"Novo Osasco",
						"Padroeira",
						"Pestana",
						"Piratininga",
						"Portal D'oeste",
						"Presidente Altino",
						"Quitaúna",
						"Raposo Tavares",
						"Recanto Rosas",
						"Rochdale",
						"Santa Fé",
						"Santa Maria",
						"Santo Antônio",
						"São Pedro",
						"Três Montanhas",
						"Umuarama",
						"Veloso",
						"Vila Campesina",
						"Vila Comend Anunziato",
						"Vila Julieta",
						"Vila Menck",
						"Vila Osasco",
						"Vila Prado",
						"Vila Remédios",
						"Vila Yara",
						"Vila Yolanda"
					]
				},
				{
					nome: "Pirapora do Bom Jesus",
					bairros: [
						"Balneário Monte Carlo",
						"Barragem",
						"Centro",
						"Chácara Boa Vista",
						"Chácara Porto Velho",
						"Chanceler São Bento",
						"Comunidade Jesus",
						"Estrada Barragem",
						"Fazenda do Outro Lado",
						"Fazenda Lolli",
						"Fazenda Outro Lado",
						"Green Hills Residencial",
						"Icaveta Cima",
						"Itaguara Park",
						"Itaquara Park",
						"Itaquara Parque",
						"Itaqueri",
						"Jardim Bom Jesus",
						"Jardim Morro Branco",
						"Jdbom Jesus",
						"Km 60",
						"Loteamento Palazzolli",
						"Morro Branco",
						"Paiol",
						"Paiol 1",
						"Paisagem Japi",
						"Park Payol",
						"Parque Paiol",
						"Parque Payol",
						"Parque Payol I",
						"Parque Payol I E Ii",
						"Parque Payol Ii",
						"Payol I",
						"Pirapora",
						"Pirapora Bom Jesus",
						"Pirapora Jesus",
						"Ponunduva",
						"Prx Vila Lolli",
						"Sítio Bandeirantes",
						"Sítio Itaquiri",
						"Vila Nova"
					]
				},
				{
					nome: "Santana de Parnaíba",
					bairros: [
						"Balneário Monte Carlo",
						"Barragem",
						"Centro",
						"Chácara Boa Vista",
						"Chácara Porto Velho",
						"Chanceler São Bento",
						"Comunidade Jesus",
						"Estrada Barragem",
						"Fazenda do Outro Lado",
						"Fazenda Lolli",
						"Fazenda Outro Lado",
						"Green Hills Residencial",
						"Icaveta Cima",
						"Itaguara Park",
						"Itaquara Park",
						"Itaquara Parque",
						"Itaqueri",
						"Jardim Bom Jesus",
						"Jardim Morro Branco",
						"Jdbom Jesus",
						"Km 60",
						"Loteamento Palazzolli",
						"Morro Branco",
						"Paiol",
						"Paiol 1",
						"Paisagem Japi",
						"Park Payol",
						"Parque Paiol",
						"Parque Payol",
						"Parque Payol I",
						"Parque Payol I E Ii",
						"Parque Payol Ii",
						"Payol I",
						"Pirapora",
						"Pirapora Bom Jesus",
						"Pirapora Jesus",
						"Ponunduva",
						"Prx Vila Lolli",
						"Sítio Bandeirantes",
						"Sítio Itaquiri",
						"Vila Nova"
					]
				},
				{
					nome: "Caieiras",
					bairros: [
						"Alpes Caieiras",
						"Alpes de Caieiras",
						"Bairro Laranjeiras",
						"Barreiro",
						"Calcarea",
						"Calcária",
						"Calcária Ivm",
						"Casa Habitacional Isaías Matiazo",
						"Centro",
						"Conjunto Habitacional Isaías Matiazo",
						"Cresciuma",
						"Ivm",
						"Jardim dos Eucaliptos",
						"Jardim Esperança",
						"Jardim Eucaliptos",
						"Jardim Eucaliptus",
						"Jardim Helena",
						"Jardim Marcelino",
						"Jardim Monte Alegre",
						"Jardim N Verde I",
						"Jardim Planalto",
						"Jardim Santo Antônio",
						"Jardim São Camilo",
						"Jardim São Francisco",
						"Jardim Só Francisco",
						"Jardim Tereza",
						"Jardim Vera Teresa",
						"Jardim Vera Tereza",
						"Jardim Virgínia",
						"Jardim Vitória",
						"Laranjal",
						"Laranjeiras",
						"Leão",
						"Melhoramentos ",
						"Morro Grande",
						"Nova Caieiras",
						"Nova Era",
						"Novo Pinheiros",
						"Parque Industrial Araucárias",
						"Parque Santa Ines",
						"Parque Santa Ines Ivm",
						"Parque São Rafael",
						"Parque Suíça",
						"Portal das Laranjeiras",
						"Portal Laranjeiras",
						"Real Parque",
						"Região Central",
						"Residencial Vala Verde",
						"Santa Aparecida",
						"Santa Ines",
						"Serpa",
						"Sítio Aparecida",
						"Valverde Laranjeiras",
						"Vera Tereza",
						"Vila Ajoa",
						"Vila Angélica",
						"Vila dos Pinheiros I",
						"Vila Gertrudes",
						"Vila Industrial",
						"Vila Maria",
						"Vila Miraval",
						"Vila Miraval I",
						"Vila Pinheiros",
						"Vila Rosina",
						"Vila São João"
					]
				},
				{
					nome: "Cajamar",
					bairros: [
						"Água Fria",
						"Aldeia do Sol",
						"Alpes Araçás",
						"Alpes dos Araçás",
						"Altos de Jordanesia",
						"Altos Jordanesia",
						"Altos Jordanesia Jordanesia",
						"Bom Sucesso",
						"Centro",
						"Colina M L Jordanesia",
						"Colina Maria Luíza",
						"Distrito Industrial",
						"Empr Paineira - Jordanesia",
						"Empresarial Anhanguera",
						"Empresarial Colina",
						"Empresarial dos Eucaliptos",
						"Empresarial G Poço Jordanesia",
						"Empresarial Gato Preto",
						"Empresarial Itaim Polvilho",
						"Empresarial M C Polvilho",
						"Empresarial Mirante Cajamar",
						"Empresarial Mirante de Cajamar",
						"Empresarial Poço Jordanesia",
						"Gato Preto",
						"Guaturinho",
						"Ipês",
						"Ipês Polvilho",
						"Jardim Bela Vista",
						"Jardim Bela Vista I",
						"Jardim Penteado",
						"Jardim Santa Rita",
						"Jardins Polvilho",
						"Jordanesia",
						"Jordanesia Jordanesia",
						"Maria Luíza",
						"Mini Distrito Industrial",
						"Panorama",
						"Panorama - Polvilho",
						"Panorama II",
						"Panorama Polvilho",
						"Paraíso",
						"Paraíso - Polvilho",
						"Paraíso Polvilho",
						"Parque Paraíso",
						"Parque São Roberto",
						"Parque São Robertojordanesia",
						"Pinheiros",
						"Polvilho",
						"Polvilho Polvilho",
						"Ponunduva",
						"Portais",
						"Portais Polvilho",
						"Portal dos Ipês Ii",
						"Santa Terezinha",
						"Santa Terezinha Jordanesia",
						"São Benedito Jordanesia",
						"São Luiz",
						"São Luiz Polvilho",
						"São Roberto",
						"São Roberto Jordanesia",
						"Scorpius II",
						"Serra dos Lagos Jordanesia",
						"Servidão Cristais",
						"Servidão Lagos",
						"Sítio Santo Antônio",
						"Vau Novo",
						"Village Scorpius I"
					]
				},
				{
					nome: "Francisco Morato",
					bairros: [
						"Água Fria",
						"Aldeia do Sol",
						"Alpes Araçás",
						"Alpes dos Araçás",
						"Altos de Jordanesia",
						"Altos Jordanesia",
						"Altos Jordanesia Jordanesia",
						"Bom Sucesso",
						"Centro",
						"Colina M L Jordanesia",
						"Colina Maria Luíza",
						"Distrito Industrial",
						"Empr Paineira - Jordanesia",
						"Empresarial Anhanguera",
						"Empresarial Colina",
						"Empresarial dos Eucaliptos",
						"Empresarial G Poço Jordanesia",
						"Empresarial Gato Preto",
						"Empresarial Itaim Polvilho",
						"Empresarial M C Polvilho",
						"Empresarial Mirante Cajamar",
						"Empresarial Mirante de Cajamar",
						"Empresarial Poço Jordanesia",
						"Gato Preto",
						"Guaturinho",
						"Ipês",
						"Ipês Polvilho",
						"Jardim Bela Vista",
						"Jardim Bela Vista I",
						"Jardim Penteado",
						"Jardim Santa Rita",
						"Jardins Polvilho",
						"Jordanesia",
						"Jordanesia Jordanesia",
						"Maria Luíza",
						"Mini Distrito Industrial",
						"Panorama",
						"Panorama - Polvilho",
						"Panorama II",
						"Panorama Polvilho",
						"Paraíso",
						"Paraíso - Polvilho",
						"Paraíso Polvilho",
						"Parque Paraíso",
						"Parque São Roberto",
						"Parque São Robertojordanesia",
						"Pinheiros",
						"Polvilho",
						"Polvilho Polvilho",
						"Ponunduva",
						"Portais",
						"Portais Polvilho",
						"Portal dos Ipês Ii",
						"Santa Terezinha",
						"Santa Terezinha Jordanesia",
						"São Benedito Jordanesia",
						"São Luiz",
						"São Luiz Polvilho",
						"São Roberto",
						"São Roberto Jordanesia",
						"Scorpius II",
						"Serra dos Lagos Jordanesia",
						"Servidão Cristais",
						"Servidão Lagos",
						"Sítio Santo Antônio",
						"Vau Novo",
						"Village Scorpius I"
					]
				},
				{
					nome: "Franco da Rocha",
					bairros: [
						"Aldeia Ivoturucaia",
						"Campos São Benedito",
						"Centro",
						"Chácara Bom Tempo",
						"Chácara Colinas",
						"Chácara São Luiz",
						"Chs do Rosário",
						"Chs Maristela",
						"Chs São José",
						"Companhia Fazenda Belém",
						"Cristais",
						"Distrito Industrial",
						"dos Cristais",
						"Estância Green Valley",
						"Estância Lago Azul",
						"Glebas",
						"Jardim Alice",
						"Jardim Alpino",
						"Jardim Benintendi",
						"Jardim Cedro do Líbano",
						"Jardim Cruzeiro",
						"Jardim das Colinas",
						"Jardim das Jabuticabeiras",
						"Jardim dos Bandeirantes",
						"Jardim dos Lagos",
						"Jardim dos Reis",
						"Jardim Jabuticabeiras",
						"Jardim Lagos",
						"Jardim Lagos II",
						"Jardim Luciana",
						"Jardim Luíza",
						"Jardim Monte Verde",
						"Jardim Progresso",
						"Jardim Santa Filomena",
						"Jardim Sinki",
						"Jardim União",
						"Lago Azul Ortiz",
						"Mato Dentro",
						"Parque dos Eucaliptos",
						"Parque Eucaliptos",
						"Parque Industrial",
						"Parque Lanel",
						"Parque Monte Verde",
						"Parque Montreal",
						"Parque Munhos",
						"Parque Paulista",
						"Parque Pretoria",
						"Parque Santa Delfa",
						"Parque Vitória",
						"Polo Industrial",
						"Portal Alamedas",
						"Portal das Alamedas",
						"Portal Estação",
						"Pouso Alegre",
						"Recanto da Lapa",
						"Recanto Lapa",
						"Sete Voltas",
						"Sítio Borda Mata",
						"Sítio Marilene",
						"Taboão",
						"Vargem Grande",
						"Vila Alves",
						"Vila Amália",
						"Vila Artur Sestini",
						"Vila Bazu",
						"Vila Bela",
						"Vila Cariri",
						"Vila Carmela de Túlio",
						"Vila dos Comerciários",
						"Vila Eliza",
						"Vila Francisco de Túlio",
						"Vila Francisco Túlio",
						"Vila Guarani",
						"Vila Humbelina",
						"Vila Ida",
						"Vila Irma",
						"Vila Josefina",
						"Vila Lanfranchi",
						"Vila Leopolis",
						"Vila Machado",
						"Vila Maggi",
						"Vila Margarida",
						"Vila Martinho",
						"Vila Olinda",
						"Vila Palmares",
						"Vila Ramos",
						"Vila Rosa",
						"Vila Rosalina",
						"Vila Santista",
						"Vila São Benedito",
						"Vila Vera Cruz",
						"Vila Zanela",
						"Villa Verde"
					]
				},
				{
					nome: "Mairiporã",
					bairros: [
						"5ª dos Carvalhos",
						"Afonso Esteves",
						"Aldeia de Mairiporã",
						"Aldeia Pitoresca",
						"Alpes Cantareira",
						"Alpes da Cantareira",
						"Alpes Mairiporã",
						"Apolinário",
						"B Capoavinha",
						"Baía Branca",
						"Bairro Palmeira",
						"Barreiro",
						"Boa Vista",
						"Bom Jesus",
						"Bom Jesus C T Preta",
						"Bom Jesus Capela Terra Preta",
						"Caceia",
						"Campo Cantareira",
						"Campo Mairiporã",
						"Campos Mairiporã",
						"Cantareira",
						"Capoava",
						"Capoavinha",
						"Capuava",
						"Caraguatá",
						"Cardosos",
						"Centro",
						"Cerros Mairiporã",
						"Cerros Verdes",
						"Chácara Arante",
						"Chácara Arantes",
						"Chácara Bela Vista",
						"Chácara Colônia Cantareira",
						"Chácara Dom Bosco",
						"Chácara Eucaliptos",
						"Chácara Lago Alpino",
						"Chácara Lenci Flora",
						"Chácara Mariflores",
						"Chácara Mirim",
						"Chácara Recanto Arsil",
						"Chácara Santa Fé",
						"Chácara São Jorge",
						"Chácara Três Meninas",
						"Chácara Veraneio",
						"Chácara Verde",
						"Champs E Village",
						"Cidade Jardim",
						"Cidae Jardim",
						"Cinco Lagos Santa Maria",
						"Colinas I",
						"Colinas II",
						"Colinas M I",
						"Colinas M II",
						"Colinas M Ii - T Preta",
						"Condomínio M Flores",
						"Condomínio Residencial Hortências",
						"Condomínio Suíça Cantareira",
						"Conjunto Mantiqueira",
						"Conjunto Residencial Mantiqueira",
						"Corumbá",
						"das Palmeiras",
						"Distrito Industrial Terra Preta",
						"Divisa",
						"do Marciano",
						"dos Cardodo",
						"Ecológico Madre",
						"Encosta Cantareira",
						"Estância Maria",
						"Estância Santo Antônio",
						"Estrada do Barreiro",
						"Estrada Santo Antônio",
						"Fazenda Cantareira",
						"Fazenda São Vicente",
						"Fernão Dias",
						"Gabão",
						"Hortolândia",
						"Hortolândia Lotes",
						"Imperador Cantareira",
						"Interlagos Village",
						"Itaim",
						"Itaimmato Dentro",
						"Jardim 5 L Santa Mar",
						"Jardim 5 Lagos",
						"Jardim Augusto Coimb",
						"Jardim Augusto Coimbra",
						"Jardim Bela Vista",
						"Jardim Boa Vista",
						"Jardim Cantareira",
						"Jardim Capoavinha",
						"Jardim Capri",
						"Jardim Capuavinha",
						"Jardim Carpi",
						"Jardim Carpinteiro",
						"Jardim Celeste",
						"Jardim Cinco Lagos",
						"Jardim Cinco Lagos Santa Maria",
						"Jardim Coimbra",
						"Jardim da Lagoa",
						"Jardim da Montanha",
						"Jardim dos Jacarandás",
						"Jardim Esperança",
						"Jardim Esplanada",
						"Jardim Ester",
						"Jardim Fernão Dias",
						"Jardim Flor Bragança",
						"Jardim Flor de Braganc",
						"Jardim Flor de Bragança",
						"Jardim Galrão",
						"Jardim Gibeon",
						"Jardim H Martins",
						"Jardim Henrique Martins",
						"Jardim Irara Branca",
						"Jardim Jacarandás",
						"Jardim Lago Cantareira",
						"Jardim Leonor",
						"Jardim Lúcia",
						"Jardim Lúcia - Terra Preta",
						"Jardim Mairi",
						"Jardim Mairiporã",
						"Jardim Mairiporã I",
						"Jardim Mairiporã II",
						"Jardim Maria Antonina",
						"Jardim Maria Eugênia",
						"Jardim Maria Fernanda",
						"Jardim Mediterrâneo",
						"Jardim Montanha",
						"Jardim Nery",
						"Jardim Nipon",
						"Jardim Nippon",
						"Jardim Nippon Terra Preta",
						"Jardim Odorico",
						"Jardim Odorico Pereira",
						"Jardim Okinaga",
						"Jardim Olimpo",
						"Jardim Oliveira",
						"Jardim Olympio",
						"Jardim Paraíso",
						"Jardim Paulista",
						"Jardim Pereira",
						"Jardim Pinheiral",
						"Jardim Primavera",
						"Jardim Prince",
						"Jardim Residencial Alice",
						"Jardim Residencial Socimar",
						"Jardim S Francisco",
						"Jardim S Francisco Ii",
						"Jardim Samambaia",
						"Jardim Samambaias",
						"Jardim Sandra I",
						"Jardim Sandra II",
						"Jardim Santa Branca",
						"Jardim Santa Filomena II",
						"Jardim Santana",
						"Jardim São Francisco",
						"Jardim São Francisco Ii",
						"Jardim São Gonçalo",
						"Jardim São Vicente",
						"Jardim Serra",
						"Jardim Serra Cantareira",
						"Jardim Sierra Madre",
						"Jardim Sol Nascente",
						"Jardim Spada",
						"Jardim Suíço",
						"Jardim Suisso",
						"Jardim Tercasa",
						"Jardim Vanessa",
						"Jardim Vaneza",
						"Jardim Zilman",
						"Jardins 5 Lagos",
						"Jundiaizinho",
						"Jundiazinho",
						"Juqueri-mirim",
						"Km1",
						"Lago do Imperador",
						"Lagos Imperador",
						"Lavapés",
						"Loteamento Saturnino Silva",
						"Mairiporã",
						"Mantiqueira",
						"Marmeleiro",
						"Marmelo",
						"Mato Dentro",
						"Mirante Lago Azul",
						"Mirante Mantiqueira",
						"Moinho",
						"Morro Vermelho",
						"N Juqueri",
						"Náutico Cantareira",
						"Nova Juqueri",
						"Núcleo Residencial Sabesp",
						"Nunes",
						"Oásis Paulista",
						"Olho D'água",
						"Ouro Verde",
						"Paineira Mairiporã",
						"Palhinha",
						"Paq Náutico Cant",
						"Parque Bariloche",
						"Parque Cabreúva",
						"Parque Cerros Verdes",
						"Parque Dinamarca",
						"Parque Imperador Cantareira",
						"Parque Imperial",
						"Parque Industrial II",
						"Parque Lago do Barreiro",
						"Parque Lagoa Barreiro",
						"Parque Moinho",
						"Parque Náutico",
						"Parque Náutico Cantareira",
						"Parque Náutico Cantareira B",
						"Parque Nova Friburgo",
						"Parque Nova Suíça",
						"Parque Novo Friburgo",
						"Parque Novo Hamburgo",
						"Parque Novo Mundo",
						"Parque Petrópolis",
						"Parque Petrópolis III",
						"Parque Petrópolis IV",
						"Parque Petrópolis Vii",
						"Parque Petrópolis Viii",
						"Parque Petrópolis Vila",
						"Parque Petrópolis X",
						"Parque Residencial Belopolis",
						"Parque Residencial Cantareira",
						"Parque Residencial Igapó",
						"Parque Suíço",
						"Parque Suíço Cantare",
						"Parque Suíço Mata Fria",
						"Parque Terezópolis Ponta",
						"Parque Votorantim",
						"Picada Nic Center",
						"Pico do Olho D'água",
						"Pirucaia",
						"Portal Colina",
						"Portal I",
						"Quinta Carvalhos",
						"Quintas Boa Vista",
						"Quintas Carvalhos",
						"Quintas Sol",
						"Rancho Grande",
						"Recanto Ceu Azul",
						"Recanto Lago",
						"Recanto Paraíso",
						"Recanto Vila Velha",
						"Recanto Vista Alegre",
						"Refúgio Serra",
						"Remédios",
						"Residencial Belopolis",
						"Residencial Nova Mairiporã",
						"Residencial Village",
						"Rio Acima",
						"Roseira",
						"Rua Acima",
						"Samambaia",
						"Santa Branca",
						"Santa Ines",
						"Santo Agostinho",
						"Santo Antônio",
						"São Francisco II",
						"São Gabriel Jaboticabal",
						"São José",
						"São Luiz",
						"São Vicente",
						"Sausalito",
						"Sausalito Sul",
						"Serra Cantareir",
						"Serra da Cantareira",
						"Serra Preta",
						"Servidão Cantareira",
						"Sítio Beija Flor",
						"Sítio Beija-flor",
						"Sítio do Pica Pau",
						"Sítio Morro Primaveras",
						"Sítio Sabiá",
						"Sossego",
						"Tapera Grande",
						"Terra Petra",
						"Terra Preta",
						"Terre Preta",
						"Vales Flores",
						"Vila Boaci",
						"Vila Boassi",
						"Vila Corumbá",
						"Vila Flores",
						"Vila Friburgo",
						"Vila Ipanema",
						"Vila Ipanema Alta",
						"Vila Machado",
						"Vila N",
						"Vila Nova",
						"Vila Nova Juqueri",
						"Vila Paula",
						"Vila Popular",
						"Vila Remédios",
						"Vila Renascença",
						"Vila Rica",
						"Vila S José",
						"Vila Sabesp",
						"Vila Santa Cruz",
						"Vila Santo Agostinho",
						"Votarantim",
						"Votorantim",
						"Ypeville"
					]
				},
				{
					nome: "Cotia",
					bairros: [
						"Água Espraiada - Caucaia Alto",
						"Água Espraiada Caucaia Alto",
						"Aguaçaí",
						"Algarve",
						"Alto Serra",
						"Altos Caucaia - Caucaia Alto",
						"Altos Caucaia Caucaia Alto",
						"Apache",
						"Bairro Graça",
						"Bairro Tijuco Preto",
						"Bosque do Vianna",
						"Bosque Vianna",
						"Brotas",
						"Brotascaucaia do Alto",
						"Cachoeira",
						"Caputera",
						"Carmo Messias",
						"Centreville",
						"Centro",
						"Centro - Caucaia Alto",
						"Centro Caucaia do Alto",
						"Chácara Atalaia",
						"Chácara Canta Galo",
						"Chácara das Rosas",
						"Chácara Eliana",
						"Chácara Granja Velha",
						"Chácara Lagos",
						"Chácara Nossa Senhora de Fátima",
						"Chácara Nossa Senhora Fátima",
						"Chácara Nossa Senhora Fátima Taboleiro Verde",
						"Chácara Ondas Verdes",
						"Chácara Pavoeiro",
						"Chácara Real - Caucaia Alto",
						"Chácara Recanto",
						"Chácara Recanto Verde",
						"Chácara Remanso - Caucaia Alto",
						"Chácara Represinha",
						"Chácara Rincão",
						"Chácara Roselândia",
						"Chácara Santa Maria",
						"Chácara São José",
						"Chácara Tropical - Caucaia Alto",
						"Chácara Uemura",
						"Chácara Vista Alegre",
						"Colina",
						"Colinas Cotia",
						"Colinas de Cotia",
						"Colinas de São Fernando",
						"Colinas São Fernando",
						"Colonial Vila - C Alto",
						"Colonial Village",
						"Condomínio Graças",
						"da Capelinha",
						"das Pedras",
						"do Tijuco Preto",
						"dos Mendes Caucaia do Alto",
						"dos Neves Caucaia do Alto",
						"dos Pereiras Caucaia do Alto",
						"Esmeralda Park",
						"Graça",
						"Gramado",
						"Gramado I",
						"Granja Caiapia",
						"Granja Carneiro Viana",
						"Granja Carolina",
						"Granja Clotilde",
						"Granja Tadao Nishikawa",
						"Granja Viana",
						"Granja Viana II",
						"Horizontal Park",
						"Ibiuna",
						"Inhambuca",
						"Invade Ci E Is",
						"Jardim Adelina",
						"Jardim Ana Cristina - Caucaia Alto",
						"Jardim Araruama",
						"Jardim Arco-íris",
						"Jardim Atalaia",
						"Jardim Barbacena",
						"Jardim Barro Branco",
						"Jardim Belizario",
						"Jardim Caiapia",
						"Jardim Carmel",
						"Jardim Central",
						"Jardim Cerejeiras",
						"Jardim Cláudio",
						"Jardim Colibri",
						"Jardim Cotia",
						"Jardim da Glória",
						"Jardim das Cerejeiras",
						"Jardim das Flores",
						"Jardim das Graças",
						"Jardim Dinorah",
						"Jardim do Engenho",
						"Jardim do Rio Cotia",
						"Jardim dos Ipês",
						"Jardim Eliane",
						"Jardim Elias",
						"Jardim Empirio",
						"Jardim Engenho",
						"Jardim Estela Mari",
						"Jardim Flores",
						"Jardim Fontana",
						"Jardim Glória",
						"Jardim Guerreiro",
						"Jardim Honoria",
						"Jardim Ipês",
						"Jardim Ísis",
						"Jardim Japão - Caucaia Alto",
						"Jardim Lambreta",
						"Jardim Lavapés das Graças",
						"Jardim Leonor",
						"Jardim Lina",
						"Jardim M Vila Pinheiros",
						"Jardim Maria Tereza",
						"Jardim Mediterrâneo",
						"Jardim Miranda",
						"Jardim Monte Santo",
						"Jardim Monte Verde - Caucaia Alto",
						"Jardim Monte Verde Caucaia Alto",
						"Jardim Nara Lúcia",
						"Jardim Nomura",
						"Jardim Nossa Senhora das Graças",
						"Jardim Nossa Senhora Graças",
						"Jardim Nova Coimbra",
						"Jardim Nova Cotia",
						"Jardim Nova Vida",
						"Jardim Oliveiras - Caucaia Alto",
						"Jardim Panorama",
						"Jardim Passargada I",
						"Jardim Pereiras - Caucaia Alto",
						"Jardim Pereiras Caucaia Alto",
						"Jardim Petrópolis",
						"Jardim Pioneira",
						"Jardim Primavera",
						"Jardim Rebelato",
						"Jardim Recanto Suave",
						"Jardim Rio Cotia",
						"Jardim Rio das Pedras",
						"Jardim Rosalina",
						"Jardim Rosemary",
						"Jardim Sabiá",
						"Jardim San Ressore - Caucaia Alto",
						"Jardim Sandra",
						"Jardim Santa Izabel",
						"Jardim Santa Maria",
						"Jardim Santa Paula",
						"Jardim Santana",
						"Jardim São Luiz",
						"Jardim São Luiz - Caucaia Alto",
						"Jardim São Luiz Caucaia do Alto",
						"Jardim São Miguel",
						"Jardim São Paulo II",
						"Jardim São Pedro",
						"Jardim São Vicente",
						"Jardim Semiramis",
						"Jardim Torino",
						"Jardim Wanda",
						"Lageadinho",
						"Maranhão",
						"Moinho Velho",
						"Morada Santa Fé",
						"Nakamura Park",
						"Nunes",
						"Outeiro de Passargada",
						"Outeiro Passargada",
						"Paisagem Casa Grande",
						"Paisagem Renoir",
						"Palos Verdes",
						"Parque Alexandre",
						"Parque Bahia",
						"Parque das Rosas",
						"Parque Dom Henrique",
						"Parque Frondoso",
						"Parque Industrial San José",
						"Parque Isaac Pires",
						"Parque Miguel Mirizola",
						"Parque Mirante da Mata",
						"Parque Mirante Mata",
						"Parque Monjolo",
						"Parque Paulistano",
						"Parque Rincão",
						"Parque Rizzo",
						"Parque Rizzo II",
						"Parque Santa Rita Cássia",
						"Parque Santa Rita de Cássia",
						"Parque São George",
						"Parque São Paulo",
						"Parque Silvino Pereira",
						"Parque Turiguara",
						"Pedras",
						"Pereiras",
						"Petit Village",
						"Pinheiros Tênis Village",
						"Pinus Park",
						"Pitas",
						"Planalto",
						"Portal da Primavera",
						"Portal do Santa Paula",
						"Portal Primavera",
						"Portal Roselândia",
						"Portão",
						"Prox Chácara Rincão",
						"Prox Chácara Rincão G Iii",
						"Prox Jardim São Luís",
						"Pununduva",
						"Quinta Ângicos",
						"Recanto Arco Verde",
						"Recanto dos Victor's",
						"Recanto Pássaros",
						"Recanto Verde",
						"Recanto Victor's",
						"Recanto Vista Alegre",
						"Residencial Park",
						"Residencial Pastoreiro",
						"Residencial Recanto Verde",
						"Ressaca",
						"San Diego Park",
						"San Fernando Park",
						"Santana",
						"São Paulo II",
						"Sítio Boa Vista",
						"Taboleiro Verde",
						"Terras de São Felipe",
						"Tijuco Preto",
						"Vila Clara",
						"Vila de São Fernando",
						"Vila Hortência",
						"Vila Industrial",
						"Vila Jovina",
						"Vila Monte Serrat",
						"Vila Santa Terezinha",
						"Vila Santo Antônio",
						"Vila Santo Antônio Carap",
						"Vila Santo Antônio do Portão",
						"Vila Santo Antônio Portão",
						"Vila São Area Carapicuíba",
						"Vila São Fernando",
						"Vila São Francisco de Assis",
						"Vila São Joaquim",
						"Vila São Roque - Caucaia Alto"
					]
				},
				{
					nome: "Embu das Artes",
					bairros: [
						"Água Morna",
						"Capuava",
						"Centro",
						"Cercado Grande",
						"Chácara Ana Lúcia",
						"Chácara Bartira",
						"Chácara Bosque Embu",
						"Chácara Caxingui",
						"Chácara Embu Colonial",
						"Chácara Jardim Colibri",
						"Chácara Marajuara",
						"Chácara Maria Alice",
						"Chácara Pinheirinho",
						"Chácara Pirajussara",
						"Chácara Santa Maria",
						"Chácara São Cristóvão",
						"Chácara São Marcos",
						"Chácara Uirapuru",
						"Chs Ana Lúcia",
						"Chs Aurora",
						"Chs Bartira",
						"Chs Caxingui",
						"Chs Lídia",
						"Chs São Cristóvão",
						"Condomínio Meu Recanto",
						"Conjunto Habitacional Embu N",
						"Conjunto Residencial Vila Carvalho",
						"Cooperativa",
						"Desembargador Aroaldo Azevedo",
						"Desmembramento Prado Rangel",
						"Embu-mirim",
						"Engenho Velho",
						"Estância de Embuarama",
						"Gramado",
						"Jardim Ângela",
						"Jardim Arabutan",
						"Jardim Batista",
						"Jardim Bela Vista",
						"Jardim Campo Limpo",
						"Jardim Casa Branca",
						"Jardim Castilho",
						"Jardim Colégio",
						"Jardim Colinas",
						"Jardim Cultura Física",
						"Jardim da Luz",
						"Jardim de Lourdes",
						"Jardim do Colégio",
						"Jardim Dom José",
						"Jardim dos Moraes",
						"Jardim Elisa",
						"Jardim Embuema",
						"Jardim Emílio Carlos",
						"Jardim Estela",
						"Jardim Fabiana",
						"Jardim Ferreira",
						"Jardim Flórida",
						"Jardim Flórida Novo",
						"Jardim Indaiá",
						"Jardim Independência",
						"Jardim Independência II",
						"Jardim Irapiranga",
						"Jardim Irene",
						"Jardim Itatiaia",
						"Jardim Júlia",
						"Jardim Jurema",
						"Jardim Liberdade",
						"Jardim Lourdes",
						"Jardim Luz",
						"Jardim Magali",
						"Jardim Magaly",
						"Jardim Maranhão",
						"Jardim Marina",
						"Jardim Mascarenhas",
						"Jardim Mimas",
						"Jardim Moraes",
						"Jardim Nayara",
						"Jardim Nossa Senhora de Fátima",
						"Jardim Nossa Senhora Fátima",
						"Jardim Nova República",
						"Jardim Novo Campo Limpo",
						"Jardim Novo Embu",
						"Jardim Olímpia",
						"Jardim Olímpia Itatuba",
						"Jardim Oliveiras",
						"Jardim Pindorama",
						"Jardim Pinheirinho",
						"Jardim Pinheiros",
						"Jardim Presidente Kennedy",
						"Jardim Sadie",
						"Jardim Santa Bárbara",
						"Jardim Santa Clara",
						"Jardim Santa Emília",
						"Jardim Santa Luzia",
						"Jardim Santa Maria",
						"Jardim Santa Rita",
						"Jardim Santa Rosa",
						"Jardim Santa Tereza",
						"Jardim Santa Tereza Novo",
						"Jardim Santo Antônio",
						"Jardim Santo Eduardo",
						"Jardim São Francisco",
						"Jardim São Luiz",
						"Jardim São Marcos",
						"Jardim São Vicente",
						"Jardim Sérgio",
						"Jardim Silvana",
						"Jardim Sílvia",
						"Jardim Taima",
						"Jardim Tomé",
						"Jardim Valo Verde",
						"Jardim Vazame",
						"Jardim Vila Alegre",
						"Jardim Vista Alegre",
						"Jardim Vitória",
						"Maria Auxiliadora",
						"Moinho Velho",
						"Parque Caetés",
						"Parque das Chácaras",
						"Parque Esplanada",
						"Parque Esplanada Embu",
						"Parque Francisco Rizzo",
						"Parque Industrial de Embu",
						"Parque Industrial Ramos Freitas",
						"Parque Industrial Rua Freitas",
						"Parque Jane",
						"Parque Luíza",
						"Parque Pirajussara",
						"Parque São Leonardo",
						"Pataxós",
						"Pertence Área Ci Is Eb",
						"Pindorama",
						"Pinheirinho",
						"Prox Jardim Tomé",
						"Retiro Vale Sol",
						"Sadie",
						"Santa Júlia",
						"Tingidor",
						"Vila Anchieta",
						"Vila Carmem",
						"Vila Carvalho",
						"Vila Cercado Grande",
						"Vila E Velho",
						"Vila Ísis Cristina",
						"Vila Maísa",
						"Vila Marajoara",
						"Vila Maria Auxiliadora",
						"Vila Olinda",
						"Vila Perequê",
						"Vila Real Moinho Velho",
						"Vila Regina",
						"Vila S José",
						"Vila Salim",
						"Vila São José",
						"Votorantim"
					]
				},
				{
					nome: "Embu-Guaçu",
					bairros: [
						"B dos Penteados",
						"Bairro dos Borges",
						"Bairro Itararé",
						"Barão Santa Izabel",
						"Borges",
						"Brn-stª Izabel",
						"Campo Alegre",
						"Centro",
						"Chácara Amigos",
						"Chácara Bonanza",
						"Chácara Califórnia",
						"Chácara dos Amigos",
						"Chácara Flor de Maio",
						"Chácara Florid",
						"Chácara Flórida",
						"Chácara Guaçu",
						"Chácara Itararé",
						"Chácara Itororó",
						"Chácara Libardi Schimidt",
						"Chácara Lídia Maria",
						"Chácara Narciza",
						"Chácara Nunes",
						"Chácara Oriente",
						"Chácara Serra Dourada",
						"Chácara Shimidt",
						"Chanceler Itororó",
						"Chanceler Nunes",
						"Charqueada",
						"Charqueado",
						"Chs Flórida",
						"Chs Floridas",
						"Cipó",
						"Cipó Guaçu",
						"Cipó Setor C",
						"Congonhal",
						"Digido",
						"dos Borges",
						"Embu Guaçu",
						"Fazenda da Ilha",
						"Fazenda Ilha",
						"Filipinho",
						"Flamingo",
						"Flórida",
						"Flórida II",
						"Granja Regina Maria",
						"Granjinha",
						"Guaçu",
						"Interlagos Sul",
						"Interlagos Sul - Fazenda da Ilha",
						"Itararé",
						"Jardim 3 Filhos",
						"Jardim Boa Vista",
						"Jardim Brasil",
						"Jardim Campestre",
						"Jardim Campestre III",
						"Jardim Campo Alegre",
						"Jardim das Samambaias",
						"Jardim Emília",
						"Jardim Guatemala",
						"Jardim Ipe",
						"Jardim Itororó",
						"Jardim Madalena",
						"Jardim Martins Fonte",
						"Jardim Martins Fontes",
						"Jardim Palmeiras",
						"Jardim Progresso",
						"Jardim Ramudalda Parra",
						"Jardim Romualda de Parra",
						"Jardim Romualda Parra",
						"Jardim S José",
						"Jardim S Paulo",
						"Jardim Santa Isabel",
						"Jardim Santa Maria",
						"Jardim São Paulo",
						"Jardim Três Filhos",
						"Jardim Tuiuti",
						"Jardim Valflor",
						"Lagoa Grande",
						"Loteamento Chanceler Santa Fé",
						"Mombaça",
						"Morada Colibris",
						"Paiol Velho Cipó",
						"Parque Alvorada",
						"Parque dos Borges",
						"Parque Florest Paulista",
						"Parque Imperial",
						"Parque Industrial",
						"Parque Itarar",
						"Parque Itararé",
						"Parque Miami",
						"Parque Nova Cipó",
						"Parque Oriente",
						"Parque Recreio",
						"Parque S Paulo",
						"Parque Valflor",
						"Penteado",
						"Prox Jardim Brasil",
						"Prx Subida Estrada Ceesp",
						"Recanto Campina Verde",
						"Recanto Castanheiras",
						"Recanto das Vrtentes",
						"Recanto Lagoa Grand",
						"Recanto Vertentes",
						"Recanto Vetentes",
						"Recreio Balneário Flamingo",
						"Santa Fé",
						"Santa Isabel",
						"Santa Rita",
						"Sapateiro",
						"Vala Flor",
						"Vale Florido",
						"Veraneio",
						"Veraneio Paulistinha",
						"Vila Cristina",
						"Vila Dirce",
						"Vila do Sol",
						"Vila Louro",
						"Vila Maria Rosa",
						"Vila Martins Fontes",
						"Vila Schunck",
						"Vila Shunck",
						"Vila Sol Nascente"
					]
				},
				{
					nome: "Itapecerica da Serra",
					bairros: [
						"Apiário Mirant Serra",
						"Aldeinha",
						"Bairro Hiroshi",
						"Bairro Potuvera",
						"Bairro Raposo Tavares",
						"Bairro Vargem Grande",
						"Centro",
						"Chácara Alpes",
						"Chácara Balbina",
						"Chácara da Lagoa",
						"Chácara Fischer",
						"Chácara Guarani",
						"Chácara Guarapiranga",
						"Chácara Hitoshi",
						"Chácara Italago",
						"Chácara Lagoa",
						"Chácara Palmeiras",
						"Chácara Recanto Bela Vista",
						"Chácara Santa Maria",
						"Chácara São Jorge",
						"Chácara Vista Alegre",
						"Chanceler Guarapiranga",
						"Chanceler Lagoa",
						"Cidade Santa Júlia",
						"Cidade São Pedro",
						"Condomínio Campo Belo",
						"Crispim",
						"da Lagoa",
						"Embu Mirim",
						"Embu Mirin",
						"Engenheiro Potuvera",
						"Engenho",
						"Estância Lagos",
						"Estância Panorama",
						"Estância Verde",
						"Itap Serra",
						"Itapecerica Serra",
						"Itapecirica Serra",
						"Itaquaciara",
						"Jardim Ademori",
						"Jardim Adenori",
						"Jardim Analândia",
						"Jardim Bela Vista",
						"Jardim Branca Flor",
						"Jardim Carmo",
						"Jardim Cinira",
						"Jardim Convento",
						"Jardim das Oliveiras",
						"Jardim das Palmeiras",
						"Jardim Diniz",
						"Jardim do Carmo",
						"Jardim do Carmo Ii",
						"Jardim do Edem",
						"Jardim Edem",
						"Jardim Elisa",
						"Jardim Eliza",
						"Jardim Embu Mirim",
						"Jardim Embu Mirin",
						"Jardim Esmeralda",
						"Jardim Esther",
						"Jardim Europa",
						"Jardim Horizonte Azul",
						"Jardim Idemori",
						"Jardim Imperatriz",
						"Jardim Isabel",
						"Jardim Itapecerica",
						"Jardim Itapecirica",
						"Jardim Jacira",
						"Jardim João Montezano",
						"Jardim Maria Cristina",
						"Jardim Maribel",
						"Jardim Marilu",
						"Jardim Marmarita",
						"Jardim Misalves",
						"Jardim Montesano",
						"Jardim Nisalves",
						"Jardim Nogueira",
						"Jardim Nova Santa Júlia",
						"Jardim Oliveiras",
						"Jardim Palmeiras",
						"Jardim Paraíso",
						"Jardim Petrolopis",
						"Jardim Petrópolis",
						"Jardim Pinheiros",
						"Jardim Renata",
						"Jardim S Marcos",
						"Jardim S Pedro",
						"Jardim Sampaio",
						"Jardim Santa Isabel",
						"Jardim Santa Izabel",
						"Jardim Santa Júlia",
						"Jardim Santo Alberto",
						"Jardim São Marcos",
						"Jardim São Pedro",
						"Jardim Sônia Maria",
						"Jardim Tereza Maria",
						"Jardim Valo Velho",
						"Jardim Virgínia",
						"Lagoa",
						"Lagoa da Prata",
						"Lagoa Prata",
						"Loteamento Sem Nome",
						"Mombaça",
						"Olaria",
						"Palmeiras",
						"Parque Delfim Verde",
						"Parque Horiz Azul",
						"Parque Horizonte Azul",
						"Parque Jandaia",
						"Parque Maringá",
						"Parque Paraíso",
						"Parque Paraíso G I I",
						"Parque Paraíso G II",
						"Parque Paraíso G III",
						"Parque Paraíso G IV",
						"Parque Paraíso G Vila",
						"Parque Paraíso Galeria I",
						"Parque Paraíso Galeria II",
						"Parque Paraíso Galeria IV",
						"Parque Paraíso Galeria Vi",
						"Parque Paraíso Galeria Vii",
						"Parque Paraíso IV",
						"Parque S Lourenço",
						"Parque Santa Adélia",
						"Parque Santa Amélia",
						"Parque Santo Antônio",
						"Parque São Francisco",
						"Parque São Lourenço",
						"Parque Yara Cecy",
						"Potuvera",
						"Prox Jardim Embu Mirim",
						"Prox Km Duz Nov Três",
						"Prx Jardim Jacira",
						"Recanto Campo Santo Amaro",
						"Recanto da Serra",
						"Recanto Floresta",
						"Recanto Primavera",
						"Recreio Camp Santo Amaro",
						"Recreio Campestre",
						"Recreio Primavera",
						"Refúgio Serra",
						"Ressaca",
						"San Isidoro",
						"Sítio Pinheiro",
						"Valo Velho",
						"Vila Geni",
						"Vila Guiomar",
						"Vila João Montesano",
						"Vila Lagos",
						"Vila Loire",
						"Vila Nova Pauliceia",
						"Vila Santa Maria"
					]
				},
				{
					nome: "Juquitiba",
					bairros: [
						"Andorinhas Conselheiro Proj",
						"Bairro das Rosas",
						"Bairro Palmeiras",
						"Baranbes",
						"Barnabé",
						"Barnabes",
						"Barra Mansa",
						"Belvedere",
						"Brancos",
						"Cachoeirinha",
						"Camargos",
						"Camirangas",
						"Carmos",
						"Centro",
						"Condomínio Alvorada",
						"Condomínio Morada do Sol",
						"Conselheiro Mapas",
						"das Laranjeiras",
						"das Palmeiras",
						"das Senhorinhas",
						"Distrito dos Barnabes",
						"dos Belchior",
						"dos Ritas",
						"Engano",
						"Ferreiras",
						"Floresta",
						"Garcias",
						"Godinho",
						"Jacuba",
						"Jardim das Palmeiras",
						"Jardim H Buccolini",
						"Jardim Palmeiras",
						"Juquia",
						"Juquiazinho",
						"Juquitiba",
						"Juquitiba Centro",
						"Justinos",
						"Justos",
						"Lagoas",
						"Loteamento Morada Sol",
						"Meia Légua",
						"Padeiros",
						"Palestina",
						"Palmeiras",
						"Palmeiras Barnabé",
						"Palmeirinha",
						"Pedra Lisa",
						"Pedras",
						"Pratas",
						"Prox Loteamento Olhos D'água",
						"Próximo Centro",
						"Ritas",
						"S Lorencoda Serra",
						"Senhorinha",
						"Senhorinhas",
						"Sítio São Benedito",
						"Soares",
						"Verde Jardim Shangrilá",
						"Vila Nova Juquitiba",
						"Vitalino",
						"Zona Rural"
					]
				},
				{
					nome: "São Lourenço da Serra",
					bairros: [
						"Bairro do Pocinho",
						"Barrinha",
						"Carolinos",
						"Centro",
						"Despezio",
						"dos Gonçalves",
						"dos Pratas",
						"dos Terezas",
						"Fazenda Vitória",
						"Floreal Park",
						"Floreal Parque",
						"Itatuba",
						"Jardim da Serra",
						"Jardim Serrano",
						"Loteamento H Trepiccione",
						"Mendes",
						"Paiol do Meio",
						"Palmeirinha",
						"Parte Aten Engenho",
						"Pocinho",
						"Portal",
						"Portal de São Lourenço",
						"Pratas",
						"Loteamento do Serralheiro",
						"São Lourenço Centro",
						"São Lourenço",
						"São Lourenço da Serra",
						"Shangrilá",
						"Terezas",
						"Triângulo",
						"Triângulo Azul",
						"Vargeado",
						"Vargedo",
						"Vila Rita Soares",
						"Zé Cozinheiro",
						"Zona Rural"
					]
				},
				{
					nome: "Taboão da Serra",
					bairros: [
						"Arraial Paulista",
						"Bairro Oliveiras",
						"Centro",
						"Chácara Agrindus",
						"Chanceler Agrindus",
						"Cidade Intercap",
						"Cidade Intercap Galeria I",
						"Cidade Intercap Galeria II",
						"Condomínio Iolanda",
						"Jardim Altos do Taboão",
						"Jardim América",
						"Jardim Beatriz",
						"Jardim Bom Tempo",
						"Jardim Bonanza",
						"Jardim Caner",
						"Jardim Carmelina Goncalv",
						"Jardim Clementino",
						"Jardim Comunitário",
						"Jardim Conceição",
						"Jardim da Glória",
						"Jardim Elizabete",
						"Jardim Frei Galvão",
						"Jardim Freitas Jr",
						"Jardim Glória",
						"Jardim Guaciara",
						"Jardim Guayana",
						"Jardim Helena",
						"Jardim Henriqueta",
						"Jardim Iolanda",
						"Jardim Iracema",
						"Jardim Irapuã",
						"Jardim Jussara",
						"Jardim Kuabara",
						"Jardim Leme",
						"Jardim Lotec",
						"Jardim Margarida",
						"Jardim Margaridas",
						"Jardim Maria da Costa",
						"Jardim Maria Helena",
						"Jardim Maria Luíza",
						"Jardim Maria Rosa",
						"Jardim Maria Sampaio",
						"Jardim Mirna",
						"Jardim Mituzi",
						"Jardim Monte Alegre",
						"Jardim Novo Record",
						"Jardim Oliveiras",
						"Jardim Ouro Preto",
						"Jardim Panorama",
						"Jardim Paraíso",
						"Jardim Pazini",
						"Jardim Pazzini",
						"Jardim Pedro Gonçalves",
						"Jardim Pirajussara",
						"Jardim Record",
						"Jardim Record Galeria B",
						"Jardim Record Gleba B",
						"Jardim Roberto",
						"Jardim Rocord Gleba C",
						"Jardim S Judas Tadeu",
						"Jardim S Luiz",
						"Jardim S Paulo",
						"Jardim S Rosa",
						"Jardim S Salvador",
						"Jardim Salete",
						"Jardim Salete Galeria II",
						"Jardim Santa Cecília",
						"Jardim Santa Cruz",
						"Jardim Santa Rosa",
						"Jardim Santa Terezinha",
						"Jardim Santo Onofre",
						"Jardim São João",
						"Jardim São Judas Tadeu",
						"Jardim São Mateus",
						"Jardim São Miguel",
						"Jardim São Paulo",
						"Jardim São Salvador",
						"Jardim Saporito",
						"Jardim Scandia",
						"Jardim Setor Moritz",
						"Jardim Setor Mortz",
						"Jardim Sílvia",
						"Jardim Sílvio Sampaio",
						"Jardim Snt Moritz",
						"Jardim Suina",
						"Jardim Três Irmãos",
						"Jardim Três Marias",
						"Jardim Triângulo",
						"Jardim Trianon",
						"Jardim Virgínia",
						"Jardim Vitória",
						"Jardim Wanda",
						"Morada dos Pássaros",
						"Novo Horizonte",
						"Núcleo Residencial Isabela",
						"Parque Albina",
						"Parque Assunção",
						"Parque Cigarreiras",
						"Parque I Oliveira",
						"Parque Industrial Daci",
						"Parque Industrial das Oliveiras",
						"Parque Industrial Oliveiras",
						"Parque Industrial Tabelião Serra",
						"Parque Industrial Taboão Serra",
						"Parque Jacarandá",
						"Parque Laguna",
						"Parque Marabá",
						"Parque Monte Alegre",
						"Parque Pinheiros",
						"Parque Residencial Mônica",
						"Parque S Joaquim",
						"Parque Santos Dumont",
						"Parque São Joaquim",
						"Parque Taboão",
						"Pinheiros",
						"Recanto Dospassaros",
						"Setor Madres",
						"Sítio das Madres",
						"Sítio Madres",
						"Vila Carmelina Gonçalves",
						"Vila das Oliveiras",
						"Vila Fco Remekis",
						"Vila Francisco Remeikis",
						"Vila Iasi",
						"Vila Indiana",
						"Vila Mafalda",
						"Vila Nova Bonanza",
						"Vila Oliveiras",
						"Vila Pinheiro",
						"Vila Santa Luzia",
						"Vila Sônia do Taboão"
					]
				},
				{
					nome: "Vargem Grande Paulista",
					bairros: [
						"47",
						"Bairro dos Coelhos",
						"Bairro dos Pereiras",
						"Bairro Graças",
						"Bairro Pereiras",
						"Bairro Pires",
						"Bela Vista",
						"Caminho do Sol",
						"Capela de São Pedro",
						"Capelão São Pedro",
						"Capitão Jenonimo",
						"Casa Blanca",
						"Centro",
						"Chácara Bacharel Verde",
						"Chácara Belverde",
						"Chácara Carmo",
						"Chácara do Planalto",
						"Chácara Esperança",
						"Chácara Planalto",
						"Chácara Recanto Verde G I",
						"Chácara Remanso I",
						"Chácara Remanso II",
						"Chácara Santa Mônica Galeria I",
						"Chácara Santa Mônica Gleba I",
						"Chácara São Judas Tadeu",
						"Chácara São Paulo",
						"Chanceler Santa Mônica",
						"Cidade Jardim",
						"Cidade São Pedro",
						"Colina Bandeirantes",
						"Colinas Bandeirantes",
						"Condomínio Santa Adélia",
						"das Lages",
						"do Carmo",
						"dos Coelhos",
						"Fazenda Belbancy",
						"Fazenda Carmo",
						"Fazenda do Carmo",
						"Galeria Gleba",
						"Granja Cristiana",
						"Granja Cristina",
						"Granja Suzuki",
						"Haras B Vista Gleba I",
						"Haras B Vista Gleba II",
						"Jardim Acoty",
						"Jardim Amarialdoa",
						"Jardim Aurora",
						"Jardim Bela Vista",
						"Jardim Betânia",
						"Jardim Elias",
						"Jardim Emília",
						"Jardim Europa",
						"Jardim Floresta",
						"Jardim Giane",
						"Jardim Giani",
						"Jardim Haras B Vista",
						"Jardim Haras B Vista I",
						"Jardim Haras Bela Vista",
						"Jardim Helena Maria",
						"Jardim Hermínia",
						"Jardim Madalena",
						"Jardim Marco Polo",
						"Jardim Margarida",
						"Jardim Marialda",
						"Jardim Mirador",
						"Jardim Miriam",
						"Jardim N S Aparecida",
						"Jardim Nagoya Garden",
						"Jardim Narita Garden",
						"Jardim Olímpia",
						"Jardim Portão Vermelho",
						"Jardim Santa Paula",
						"Jardim São Lucas",
						"Jardim São Marcos",
						"Jardim São Mateus",
						"Jardim Vargem Grande",
						"Km 39",
						"Km 40",
						"Km 41",
						"Km 42",
						"Km 43",
						"Km 44",
						"Km 45",
						"Km 46",
						"Lagoa",
						"Los Álamos",
						"Mariápolis Araceli",
						"Mariápolis Ginetta",
						"Matão",
						"Monte Catine",
						"Morada do Sol",
						"Morada Sol",
						"Nagoya Gardem",
						"Nara Garden",
						"Narita Garden",
						"Parque Agreste Galeria Ii",
						"Parque Agreste Gleba I",
						"Parque Agreste Gleba II",
						"Parque do Agreste",
						"Parque do Agreste Galeria I",
						"Parque Lages",
						"Parque Residencial",
						"Parque Residencial Emerson",
						"Parque Ruth Maria",
						"Parque Ruthe Maria",
						"Parque Santo Afonso",
						"Parque Santo Afonso I",
						"Parque Santo Afonso II",
						"Parque Vent Vert",
						"Planalto",
						"Portão Vermelho",
						"Prox Chácara São Paulo",
						"Prox Jardim Mirim",
						"Prx Jardim Bela Vista",
						"Prx Jardim Betânia",
						"Prx Jardim Vargem Grande",
						"Recanto do Sossego",
						"Recanto dos Pássaro",
						"Recanto Jandaia",
						"Recanto Pássaros",
						"Recanto Verde",
						"Refúgio Amigos",
						"Rene Corrêa",
						"Residencial San Diego",
						"Ruth Maria",
						"S João",
						"S Judas",
						"S Judas Tadeu",
						"S Marcos",
						"São Lucas",
						"Sossego",
						"Terras de Santa Adélia",
						"Tijuco Preto",
						"Vargem Grande",
						"Vargem Grande Paulista",
						"Vila Branco",
						"Vila Dirce",
						"Vila Feliciano",
						"Vila Friburgo",
						"Vila G Paulista",
						"Vila Industrial",
						"Vila Josefina",
						"Vila Olímpia",
						"Vila Pires",
						"Vila Pires Centro",
						"Vila São Judas Tadeu"
					]
				},
				{
					nome: "Diadema",
					bairros: [
						"Campanário",
						"Canhema",
						"Casa Grande",
						"Centro",
						"Conceição",
						"Eldorado",
						"Inamar",
						"Jardim União",
						"Piraporinha",
						"Serraria",
						"Taboão",
						"Vila Nogueira"
					]
				},
				{
					nome: "Mauá",
					bairros: [
						"Alto Boa Vista",
						"Alto da Boa Vista",
						"Capuava",
						"Centro",
						"Chácara Maria Aparecida",
						"Chácara Maria Francisca",
						"Chácara São Braz",
						"Chácara São Lucido",
						"Jardim Adelina",
						"Jardim Anchieta",
						"Jardim Aracy",
						"Jardim Araguaia",
						"Jardim Bela Vista",
						"Jardim Bogus",
						"Jardim Bom Recanto",
						"Jardim Camila",
						"Jardim Campo Verde",
						"Jardim Canadá",
						"Jardim Cerqueira Leite",
						"Jardim Colúmbia",
						"Jardim Cruzeiro",
						"Jardim Cruzeiro do Sul",
						"Jardim Éden",
						"Jardim Elizabeth",
						"Jardim Esperança",
						"Jardim Estrela",
						"Jardim Flórida",
						"Jardim Guapituba",
						"Jardim Haydee",
						"Jardim Hélida",
						"Jardim Ipe",
						"Jardim Itapark Novo",
						"Jardim Itapark Velho",
						"Jardim Itapeva",
						"Jardim Luzitano",
						"Jardim Maria Eneida",
						"Jardim Maringá",
						"Jardim Mauá",
						"Jardim Miranda D'aviz",
						"Jardim Nilza Miranda",
						"Jardim Olinda",
						"Jardim Oratório",
						"Jardim Paranavai",
						"Jardim Paulista",
						"Jardim Pedroso",
						"Jardim Pilar",
						"Jardim Planalto",
						"Jardim Primavera",
						"Jardim Quarto Centenário",
						"Jardim Rosina",
						"Jardim Santa Lídia",
						"Jardim Santista",
						"Jardim São Francisco",
						"Jardim São Gabriel",
						"Jardim São João",
						"Jardim São Jorge do Guapituba",
						"Jardim São José",
						"Jardim São Judas",
						"Jardim Sílvia Maria",
						"Jardim Sônia Maria",
						"Jardim Taquarussu",
						"Jardim Zaira",
						"Loteamento Industrial Coral",
						"Matriz",
						"Núcleo Doutor Sampaio Vidal",
						"Núcleo Sampaio Vidal",
						"Parque Alvorada",
						"Parque Bandeirantes",
						"Parque Boa Esperança",
						"Parque das Américas",
						"Parque São Vicente",
						"Recanto Vital Brasil",
						"São João",
						"Sertãozinho",
						"Sítio Bela Vista",
						"Vila América",
						"Vila Ana",
						"Vila Ana Maria",
						"Vila Assis Brasil",
						"Vila Augusto",
						"Vila Bocaina",
						"Vila Carlina",
						"Vila Correia",
						"Vila Dirce",
						"Vila Emílio",
						"Vila Falchi",
						"Vila Feital",
						"Vila Flórida",
						"Vila Guarani",
						"Vila Independência",
						"Vila João Ramalho",
						"Vila Lisboa",
						"Vila Magini",
						"Vila Mercedes",
						"Vila Morelli",
						"Vila Noêmia",
						"Vila Nossa Senhora das Vitórias",
						"Vila Nova Canaã",
						"Vila Nova Mauá",
						"Vila Oratório",
						"Vila Real",
						"Vila Santa Cecília",
						"Vila Santa Rosa",
						"Vila São Francisco",
						"Vila Tavares"
					]
				},
				{
					nome: "Santo André",
					bairros: [
						"Alto Boa Vista",
						"Alto da Boa Vista",
						"Capuava",
						"Centro",
						"Chácara Maria Aparecida",
						"Chácara Maria Francisca",
						"Chácara São Braz",
						"Chácara São Lucido",
						"Jardim Adelina",
						"Jardim Anchieta",
						"Jardim Aracy",
						"Jardim Araguaia",
						"Jardim Bela Vista",
						"Jardim Bogus",
						"Jardim Bom Recanto",
						"Jardim Camila",
						"Jardim Campo Verde",
						"Jardim Canadá",
						"Jardim Cerqueira Leite",
						"Jardim Colúmbia",
						"Jardim Cruzeiro",
						"Jardim Cruzeiro do Sul",
						"Jardim Éden",
						"Jardim Elizabeth",
						"Jardim Esperança",
						"Jardim Estrela",
						"Jardim Flórida",
						"Jardim Guapituba",
						"Jardim Haydee",
						"Jardim Hélida",
						"Jardim Ipe",
						"Jardim Itapark Novo",
						"Jardim Itapark Velho",
						"Jardim Itapeva",
						"Jardim Luzitano",
						"Jardim Maria Eneida",
						"Jardim Maringá",
						"Jardim Mauá",
						"Jardim Miranda D'aviz",
						"Jardim Nilza Miranda",
						"Jardim Olinda",
						"Jardim Oratório",
						"Jardim Paranavai",
						"Jardim Paulista",
						"Jardim Pedroso",
						"Jardim Pilar",
						"Jardim Planalto",
						"Jardim Primavera",
						"Jardim Quarto Centenário",
						"Jardim Rosina",
						"Jardim Santa Lídia",
						"Jardim Santista",
						"Jardim São Francisco",
						"Jardim São Gabriel",
						"Jardim São João",
						"Jardim São Jorge do Guapituba",
						"Jardim São José",
						"Jardim São Judas",
						"Jardim Sílvia Maria",
						"Jardim Sônia Maria",
						"Jardim Taquarussu",
						"Jardim Zaira",
						"Loteamento Industrial Coral",
						"Matriz",
						"Núcleo Doutor Sampaio Vidal",
						"Núcleo Sampaio Vidal",
						"Parque Alvorada",
						"Parque Bandeirantes",
						"Parque Boa Esperança",
						"Parque das Américas",
						"Parque São Vicente",
						"Recanto Vital Brasil",
						"São João",
						"Sertãozinho",
						"Sítio Bela Vista",
						"Vila América",
						"Vila Ana",
						"Vila Ana Maria",
						"Vila Assis Brasil",
						"Vila Augusto",
						"Vila Bocaina",
						"Vila Carlina",
						"Vila Correia",
						"Vila Dirce",
						"Vila Emílio",
						"Vila Falchi",
						"Vila Feital",
						"Vila Flórida",
						"Vila Guarani",
						"Vila Independência",
						"Vila João Ramalho",
						"Vila Lisboa",
						"Vila Magini",
						"Vila Mercedes",
						"Vila Morelli",
						"Vila Noêmia",
						"Vila Nossa Senhora das Vitórias",
						"Vila Nova Canaã",
						"Vila Nova Mauá",
						"Vila Oratório",
						"Vila Real",
						"Vila Santa Cecília",
						"Vila Santa Rosa",
						"Vila São Francisco",
						"Vila Tavares"
					]
				},
				{
					nome: "São Bernardo do Campo",
					bairros: [
						"Alto da Serra",
						"Alto Industrial",
						"Alvarenga",
						"Alves Dias",
						"Anchieta",
						"Assunção",
						"Baeta Neves",
						"Balneária",
						"Batistini",
						"Capivari",
						"Casa",
						"Centro",
						"Cooperativa",
						"Curucutu",
						"Demarchi",
						"dos Casa",
						"dos Finco",
						"Favela Jardim Silvina",
						"Ferrazópolis",
						"Independência",
						"Jardim Cláudia",
						"Jardim do Mar",
						"Jardim Farina",
						"Jardim Imperador",
						"Jardim Independência",
						"Jardim Industrial",
						"Jardim Jussara",
						"Jardim Lago",
						"Jardim Las Vegas",
						"Jardim Laura",
						"Jardim Los Angeles",
						"Jardim Maria Adelaide",
						"Jardim Nazareth",
						"Jardim Novo Horizonte",
						"Jardim O Ipe",
						"Jardim Olavo Bilac",
						"Jardim Orquídeas",
						"Jardim Petroni",
						"Jardim Regina",
						"Jardim São Luís",
						"Jordanópolis",
						"Montanhão",
						"Nova Baeta",
						"Nova Petrópolis",
						"Parque Botujuru",
						"Parque São Bernardo",
						"Parque São Bernardo Novo",
						"Parque Selecta",
						"Parque Terra Nova",
						"Parque Terra Nova II",
						"Pauliceia",
						"Planalto",
						"Rio Grande",
						"Rudge Ramos",
						"Santa Cruz",
						"Santa Terezinha",
						"Sítio Bela Vista",
						"Taboão",
						"Taquacetuba",
						"Tatetos",
						"Vila das Valsas",
						"Vila Euclídes",
						"Vila Gonçalves",
						"Vila Industrial",
						"Vila Lusitânia",
						"Vila Nogueira",
						"Vila Santa Mônica",
						"Vila Scopel",
						"Vila Tupi",
						"Vila Vianas",
						"Zanzala"
					]
				},
				{
					nome: "São Caetano do Sul",
					bairros: [
						"Barcelona",
						"Boa Vista",
						"Centro",
						"Cerâmica",
						"Fundação",
						"Jardim São Caetano",
						"Mauá",
						"Nova Gerty",
						"Olímpico",
						"Osvaldo Cruz",
						"Prosperidade",
						"Santa Maria",
						"Santa Paula",
						"Santo Antônio",
						"São José"
					]
				},
				{
					nome: "Ribeirão Pires",
					bairros: [
						"Aliança",
						"Barro Branco",
						"Bocaina",
						"Casa Vermelha",
						"Centro",
						"Centro Alto",
						"Centro de Ouro Fino Paulista",
						"Colônia",
						"Guapituba",
						"Itrapoa",
						"Km 4",
						"Pastoril",
						"Pilar Velho",
						"Ponte Seca",
						"Pouso Alegre",
						"Quarta Divisão",
						"Represa",
						"Roncon",
						"Santa Luzia",
						"Santana",
						"São Caetaninho",
						"Somma",
						"Suíssa",
						"Tanque Caio",
						"Tecelão"
					]
				},
				{
					nome: "Rio Grande da Serra",
					bairros: [
						"Acamp Anchieta",
						"Centro",
						"Chácara São Paulo",
						"Chácara Santa Fé",
						"Fazenda São Joaquim",
						"Jardim Encantado",
						"Jardim Esperança",
						"Jardim Guaripocaba",
						"Jardim Joaquim Lima",
						"Jardim Lavínia",
						"Jardim Maria Paula",
						"Jardim Novo Horizonte",
						"Jardim Oásis Paulista",
						"Jardim Palmira",
						"Jardim Rachel",
						"Jardim Santa Tereza",
						"Oásis Paulista",
						"Parque América",
						"Parque Governador",
						"Parque Indaiá",
						"Parque Pouso Alegre",
						"Parque Rio Grande",
						"Pedreira",
						"Recanto das Flores",
						"Recanto Flores",
						"Recanto Monte Alegre",
						"Rio Pequeno",
						"Santa Tereza",
						"Vila Albano",
						"Vila Arnaoud",
						"Vila Arnoud",
						"Vila Condomínio Siciliano",
						"Vila Felicidade",
						"Vila Figueiredo",
						"Vila Lavínia",
						"Vila Lopes",
						"Vila Marcos",
						"Vila Monte Alegre",
						"Vila Niwa",
						"Vila Nova Califórnia",
						"Vila Oásis Paulista",
						"Vila Ota",
						"Vila Recanto Flores",
						"Vila Rio Grande",
						"Vila Santa Tereza",
						"Vila São João",
						"Vila Suzuki",
						"Vila Tsuzuki"
					]
				}
			]
		}
	]
};
