POST http://localhost:3000/profissionais
Content-Type: application/json

{
"cpf_cnpj": "355.476.489-01",
"email": "ty5eu5t476st@ema7il.com",
"nome": "test",
"senha": "testemail",
"estado": "SP",
"cidade": "Osasco",
"bairro": "Jardim Piratininga",
"cep": "46545-485",
"telefone": "(45) 5465-4678",
"celular": "(78) 67867-8678",
"whatsapp": "(78) 67867-8678",
"tags": ["barbeiro", "encanador"]
}

###
POST http://localhost:3000/profissionais/entrar
Content-Type: application/json

{
"email": "teste@email.com",
"senha": "contateste"
}

###
GET http://localhost:3000/profissionais/69
Content-Type: application/json

###
POST http://localhost:3000/profissionais/dadosCadastrais
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjksIm5vbWUiOiJOT01FIERFIFRFU1RFIiwiY3BmX2NucGoiOiIwMDAuMDAwLjAwMC0wMCIsImVtYWlsIjoidGVzdGVAZW1haWwuY29tIiwiaWF0IjoxNTgyNzA2OTE3LCJleHAiOjE1ODI3OTMzMTd9.PajywjYdXBxbUVE5bKKVqSHFV5CSHqCZ6NmjdHq5aRY