POST http://localhost:3000/profissionais
Content-Type: application/json

{
"cpf_cnpj": "355.476.489-01",
"email": "ty5eu5t476st@ema7il.com",
"nome": "test",
"senha": "testemail",
"estado": "SP",
"cidade": "Osasco",
"bairro": "Jardim Piratininga",
"cep": "46545-485",
"telefone": "(45) 5465-4678",
"celular": "(78) 67867-8678",
"whatsapp": "(78) 67867-8678",
"tags": ["barbeiro", "encanador", 5]
}

###
POST http://localhost:3000/profissionais/entrar
Content-Type: application/json

{
"email": "juris@njr1t.com",
"senha": "q46q4656"
}